/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-compjob' : '&#xe000;',
			'icon-reouser' : '&#xe001;',
			'icon-reotrash' : '&#xe002;',
			'icon-reotaskcomp' : '&#xe003;',
			'icon-reotask' : '&#xe004;',
			'icon-reonote' : '&#xe005;',
			'icon-reomap' : '&#xe006;',
			'icon-reoimage' : '&#xe007;',
			'icon-reofolder' : '&#xe008;',
			'icon-reocheck' : '&#xe009;',
			'icon-reocamera' : '&#xe00a;',
			'icon-reobid' : '&#xe00b;',
			'icon-reoaddfolder' : '&#xe00c;',
			'icon-pendjob' : '&#xe00d;',
			'icon-acceptjob' : '&#xe00e;',
			'icon-connection' : '&#xe00f;',
			'icon-bubble' : '&#xe010;',
			'icon-bubbles' : '&#xe011;',
			'icon-bubbles-2' : '&#xe012;',
			'icon-facebook' : '&#xe013;',
			'icon-facebook-2' : '&#xe014;',
			'icon-facebook-3' : '&#xe019;',
			'icon-twitter' : '&#xe01a;',
			'icon-twitter-2' : '&#xe01b;',
			'icon-twitter-3' : '&#xe01c;',
			'icon-youtube' : '&#xe01d;',
			'icon-youtube-2' : '&#xe01e;',
			'icon-vimeo' : '&#xe01f;',
			'icon-apple' : '&#xe026;',
			'icon-android' : '&#xe027;',
			'icon-html5' : '&#xe02a;',
			'icon-html5-2' : '&#xe02b;',
			'icon-paypal' : '&#xe030;',
			'icon-paypal-2' : '&#xe031;',
			'icon-paypal-3' : '&#xe032;',
			'icon-tumblr' : '&#xe033;',
			'icon-tumblr-2' : '&#xe034;',
			'icon-Fahrenheit' : '&#xe035;',
			'icon-Celsius' : '&#xe036;',
			'icon-none' : '&#xe037;',
			'icon-compass' : '&#xe038;',
			'icon-thermometer' : '&#xe039;',
			'icon-lightning' : '&#xe03a;',
			'icon-cloudy' : '&#xe03b;',
			'icon-weather' : '&#xe03c;',
			'icon-snowy' : '&#xe03d;',
			'icon-snowy-2' : '&#xe03e;',
			'icon-windy' : '&#xe03f;',
			'icon-windy-2' : '&#xe040;',
			'icon-rainy' : '&#xe041;',
			'icon-rainy-2' : '&#xe042;',
			'icon-lightning-2' : '&#xe043;',
			'icon-cloud' : '&#xe044;',
			'icon-cloud-2' : '&#xe045;',
			'icon-cloudy-2' : '&#xe046;',
			'icon-moon' : '&#xe047;',
			'icon-sun' : '&#xe048;',
			'icon-lightning-3' : '&#xe049;',
			'icon-cloud-3' : '&#xe04a;',
			'icon-cloudy-3' : '&#xe04b;',
			'icon-weather-2' : '&#xe04c;',
			'icon-snowy-3' : '&#xe04d;',
			'icon-snowy-4' : '&#xe04e;',
			'icon-snowy-5' : '&#xe04f;',
			'icon-windy-3' : '&#xe050;',
			'icon-windy-4' : '&#xe051;',
			'icon-rainy-3' : '&#xe052;',
			'icon-rainy-4' : '&#xe053;',
			'icon-lightning-4' : '&#xe054;',
			'icon-lightning-5' : '&#xe055;',
			'icon-cloud-4' : '&#xe056;',
			'icon-lines' : '&#xe057;',
			'icon-weather-3' : '&#xe058;',
			'icon-weather-4' : '&#xe059;',
			'icon-weather-5' : '&#xe05a;',
			'icon-cloud-5' : '&#xe05b;',
			'icon-cloudy-4' : '&#xe05c;',
			'icon-snowflake' : '&#xe05d;',
			'icon-wind' : '&#xe05e;',
			'icon-windy-5' : '&#xe05f;',
			'icon-sun-2' : '&#xe060;',
			'icon-moon-2' : '&#xe061;',
			'icon-sun-3' : '&#xe062;',
			'icon-sunrise' : '&#xe063;',
			'icon-disk' : '&#xe064;',
			'icon-reoevents' : '&#xe065;',
			'icon-reoforms' : '&#xe066;',
			'icon-reologo' : '&#xe067;',
			'icon-reosetting' : '&#xe068;',
			'icon-reostarted' : '&#xe069;',
			'icon-reowebhook' : '&#xe06a;',
			'icon-arrow-left' : '&#xe06b;',
			'icon-arrow-right' : '&#xe06c;',
			'icon-cog' : '&#xe06d;',
			'icon-cloud-download' : '&#xe06e;',
			'icon-cloud-upload' : '&#xe06f;',
			'icon-mobile' : '&#xe070;',
			'icon-mobile-2' : '&#xe071;',
			'icon-tablet' : '&#xe072;',
			'icon-screen' : '&#xe073;',
			'icon-laptop' : '&#xe074;',
			'icon-pp' : '&#xe075;',
			'icon-web' : '&#xe076;',
			'icon-excel_icon' : '&#xe015;',
			'icon-qc_icon' : '&#xe016;',
			'icon-sub_task_icon' : '&#xe017;',
			'icon-b_accept' : '&#xe018;',
			'icon-b_pend' : '&#xe020;',
			'icon-j_unsent' : '&#xe021;',
			'icon-qc_accept' : '&#xe022;',
			'icon-qc_pend' : '&#xe023;',
			'icon-qc_unsent' : '&#xe024;',
			'icon-home' : '&#xe025;',
			'icon-home-2' : '&#xe028;',
			'icon-pencil' : '&#xe029;',
			'icon-user' : '&#xe02c;',
			'icon-lock' : '&#xe02d;',
			'icon-lock-2' : '&#xe02e;',
			'icon-checkmark' : '&#xe02f;',
			'icon-q_pending' : '&#xe077;',
			'icon-q_complete' : '&#xe078;',
			'icon-b_pending' : '&#xe079;',
			'icon-b_complete' : '&#xe07a;',
			'icon-pencil-2' : '&#xe07b;',
			'icon-image' : '&#xe07c;',
			'icon-images' : '&#xe07d;',
			'icon-connection-2' : '&#xe07e;',
			'icon-mobile-3' : '&#xe07f;',
			'icon-mobile-4' : '&#xe080;',
			'icon-tablet-2' : '&#xe081;',
			'icon-drawer' : '&#xe082;',
			'icon-drawer-2' : '&#xe083;',
			'icon-cog-2' : '&#xe084;',
			'icon-remove' : '&#xe085;',
			'icon-checkbox-checked' : '&#xe086;',
			'icon-checkbox-unchecked' : '&#xe087;',
			'icon-checkbox-partial' : '&#xe088;',
			'icon-radio-checked' : '&#xe089;',
			'icon-radio-unchecked' : '&#xe08a;',
			'icon-cart' : '&#xe08b;',
			'icon-cart-2' : '&#xe08c;',
			'icon-cart-3' : '&#xe08d;',
			'icon-coin' : '&#xe08e;',
			'icon-credit' : '&#xe08f;',
			'icon-screen-2' : '&#xe090;',
			'icon-lft' : '&#xe091;',
			'icon-overset' : '&#xe092;',
			'icon-plus' : '&#xe093;',
			'icon-rgt' : '&#xe094;',
			'icon-securnum' : '&#xe095;',
			'icon-textbox' : '&#xe096;',
			'icon-textfield' : '&#xe097;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};